name: EAS Build
on: 
  workflow_dispatch:

  push:
    branches:
    - staging
    - dev 

jobs:
  build-android:
    name: Install and build android app (preview)
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: android
      PROFILE: preview
    
  build-ios:
    name: Install and build ios app (preview)
    uses: ./.github/workflows/eas-build.yaml
    secrets: inherit
    with:
      PLATFORM: ios
      PROFILE: preview